#!/bin/sh
if [ -z "$1" ]
then
   echo "need file name"
   exit 1
fi
# use kotlin on java
kotlinc-jvm $1.kt -include-runtime -d $1.jar && java -jar $1.jar && rm $1.jar

# use kotlin
# NOTE: should change the file name to $1
# kotlinc main.kt && kotlin MainKt